# Generated by Django 6.0.2 on 2026-02-26 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('scans_count', models.IntegerField(default=0)),
                ('ads_watched', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Usage',
                'verbose_name_plural': 'Daily Usages',
                'db_table': 'billing_daily_usage',
            },
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('scan_limit_per_day', models.IntegerField(blank=True, null=True)),
                ('ads_enabled', models.BooleanField(default=True)),
                ('features', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'billing_plan',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CANCELED', 'CANCELED'), ('PAST_DUE', 'PAST_DUE'), ('TRIALING', 'TRIALING')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'billing_subscription',
            },
        ),
    ]
