# Generated by Django 6.0.2 on 2026-03-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="avatar",
            field=models.TextField(
                blank=True, default="", help_text="User profile avatar as base64 encoded string."
            ),
        ),
    ]
