# Generated by Django 6.0.2 on 2026-03-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_customusermodel_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="auth_provider",
            field=models.CharField(
                default="local",
                help_text="Provider used to authenticate ('local', 'google', etc.).",
                max_length=50,
            ),
        ),
    ]
