# Generated by Django 6.0.2 on 2026-03-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_customusermodel_auth_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="username",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
